insert into "User" (UserName, Position, Email, Phone, Location) values ('Laura Rodriguez', 'Director of Information Technology', 'example.email@example.com', '085-593-1922', '123 Main St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Emily Johnson', 'Engineering Manager', 'jane.smith@example.com', '115-670-5190', '123 Main St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('David Thomas', 'IT Director', 'jane.smith@example.com', '042-717-4377', '101 Pine Rd');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Elizabeth Lopez', 'Chief Technology Officer (CTO)', 'john.doe@example.com', '484-908-7372', '202 Maple Ln');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Jennifer Martinez', 'Technical Lead', 'user456@example.com', '209-879-0896', '202 Maple Ln');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Robert Wilson', 'Software Development Manager', 'testuser123@example.com', '667-253-9783', '123 Main St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Elizabeth Lopez', 'Product Manager', 'testuser123@example.com', '348-702-7117', '123 Main St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Emily Johnson', 'Chief Information Officer (CIO)', 'example.email@example.com', '401-173-9485', '456 Elm St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Laura Rodriguez', 'Engineering Manager', 'john.doe@example.com', '757-360-2362', '789 Oak Ave');
insert into "User" (UserName, Position, Email, Phone, Location) values ('John Smith', 'Technical Lead', 'example.email@example.com', '863-321-8982', '456 Elm St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('William Anderson', 'Software Development Manager', 'example.email@example.com', '571-045-8026', '101 Pine Rd');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Amanda Garcia', 'Director of Operations', 'testuser123@example.com', '715-599-2340', '202 Maple Ln');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Daniel Martinez', 'IT Director', 'testuser123@example.com', '438-649-6019', '123 Main St');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Matthew Perez', 'Chief Technology Officer (CTO)', 'user456@example.com', '754-045-0372', '101 Pine Rd');
insert into "User" (UserName, Position, Email, Phone, Location) values ('Robert Wilson', 'Engineering Manager', 'example.email@example.com', '190-226-5622', '123 Main St');
